import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Inter } from 'next/font/google';

import './globals.css';

const ITCSouvenir = localFont({
  src: './fonts/ITC Souvenir Medium.otf',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { Provider } from '@/components/ui/provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ITCSouvenir.className} ${inter.className}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
